#### general settings
gpu_ids: [ 0 ]
classes: ["NOCOVID", "COVID"]
num_classes: &num_classes 5
threshold: 0.5

#### datasets
datasets:
  mode: ECGHeartbeatCategorization
  train:
    dataset_args:
      path_to_csv: /home/malchul/work/CadrioSpike/data/pretrain/mitbih_train_split.csv
    n_workers: 10
    batch_size: 16
    augs_args: null


  val:
    dataset_args:
      path_to_csv: /home/malchul/work/CadrioSpike/data/pretrain/mitbih_test_split.csv
    n_workers: 5
    batch_size: 10
    augs_args: null

network:
  model: SimpleCNN
  input_channels: 1
  output_channels: *num_classes
  num_convs: 15
  multiplier: 1.2

# Maps output from dataset to model args
input_keys:
  ampl: x
  mask: mask
  time: time
  ampl_diff: x_diff
  angle: angle

exp_name: ""
#### path
checkpoint_path: null

#### training settings: learning rate scheme, loss
train:

  scheduler_params:
    scheduler: ExponentialLR  # Registry keyword for scheduler name
    gamma: 0.9802265618354915  # Reduces by 20

  optimizer_params:
    optimizer: AdamW
    lr: !!float 2e-4
    weight_decay: 0.001
    betas: [ 0.9, 0.999 ]

  loss_args:
    criterion: CrossEntropyLoss

  epoches: 150
  use_negative_sampling: False

  use_plt: True

  log_freq: 10
  img_log_freq: 400
  val_freq: 10
  val_steps_limit: 50
  train_steps_limit: 1000


  precision: 32
  gradient_clip_val: 0


hydra:
  run:
    dir: outputs_pretrain/${now:%Y-%m-%d}/${now:%H-%M-%S}_pretrain_${network.model}_${datasets.mode}_${exp_name}